### ISSUE TITLE
How to put the index.html file into dist directory

### ISSUE THREAD

**Issue by mrdulin** [egor-smirnov/egorsmirnov.me-examples#8]
``` js
app.get('*', function (req, res) {
    var indexPath = path.join(__dirname, 'dist/index.html');
    console.log(indexPath)
    res.sendFile(indexPath);
});
```

above code give me this error when I visit `localhost:3000`,

```
bundle.js:1 Uncaught SyntaxError: Unexpected token <
```

I want to put the `index.html` file into `dist` directory, How to do that? Thanks!

Here is my git repo https://github.com/mrdulin/react-examples

**Comment by egor-smirnov** [comment]
Hello, check one of the following webpack plugins:

https://github.com/ampedandwired/html-webpack-plugin
https://github.com/kevlened/copy-webpack-plugin
